let jobs=[];try{const raw=localStorage.getItem('tradieJobs');jobs=raw?JSON.parse(raw):[];if(!Array.isArray(jobs))jobs=[]}catch(e){jobs=[]}
let current=null,editingOpening=-1,layoutCols=2,layoutRows=1,panelConfigs=[],selectedPanel=0,hasTransom=false,transomPct=50;
const TYPES=['Awning','Casement','Double Hung','Bifold','Hinged Door','Sliding Door','Fixed'];
const typeFamilyMap={'Window':'Window','Fixed Window':'Window','Awning Window':'Window','Casement Window':'Window','Double Hung Window':'Window','Bifold Window':'Window','Door':'Door','Hinged Door':'Door','Sliding Door':'Door'};
const $=id=>document.getElementById(id);
function persist(){localStorage.setItem('tradieJobs',JSON.stringify(jobs))}
function show(id){document.querySelectorAll('main>section').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');if(id==='jobs')renderJobs();if(id==='job'&&current){$('jobTitle').textContent=current.site||'Job';$('jobInfo').textContent=current.customer||'';renderOpenings()}}
function newJob(){current=null;editingOpening=-1;$('customer').value='';$('site').value='';$('jobnotes').value='';show('new');setTimeout(()=>$('customer').focus(),30)}
function createJob(){const customer=$('customer').value.trim(),site=$('site').value.trim(),notes=$('jobnotes').value.trim();if(!customer&&!site){alert('Enter a customer or job/site.');return}current={id:Date.now(),customer,site,notes,openings:[]};jobs.unshift(current);persist();$('customer').value='';$('site').value='';$('jobnotes').value='';show('job')}
function openJob(id){current=jobs.find(j=>j.id===id)||null;if(current)show('job')}
function renderJobs(){const q=($('search').value||'').toLowerCase();const list=$('jobList');const m=jobs.filter(j=>[j.customer,j.site,j.notes].join(' ').toLowerCase().includes(q));list.innerHTML=m.length?m.map(j=>`<div class="job" data-id="${j.id}"><b>${esc(j.site||'Untitled Job')}</b><div>${esc(j.customer||'')}</div><span class="pill">${(j.openings||[]).length} openings</span></div>`).join(''):'<div class="card muted">No jobs found.</div>';list.querySelectorAll('.job').forEach(x=>x.onclick=()=>openJob(Number(x.dataset.id)))}
function setupOpening(){const room=$('room').value.trim(),h=$('height').value.trim(),w=$('width').value.trim();if(!room||!h||!w){alert('Enter room, height and width first.');return}editingOpening=-1;layoutCols=2;layoutRows=1;panelConfigs=Array.from({length:2},()=>({type:'',direction:''}));selectedPanel=0;hasTransom=false;transomPct=50;show('builder');draw()}
function setLayout(key){if(key==='1x1'){layoutCols=1;layoutRows=1}else if(key==='2x1'){layoutCols=2;layoutRows=1}else if(key==='3x1'){layoutCols=3;layoutRows=1}else if(key==='4x1'){layoutCols=4;layoutRows=1}else{layoutCols=2;layoutRows=2}const n=layoutCols*layoutRows;panelConfigs=Array.from({length:n},(_,i)=>panelConfigs[i]||({type:'',direction:''}));selectedPanel=Math.min(selectedPanel,n-1);draw()}
function editOpening(i){const o=current.openings[i];editingOpening=i;$('room').value=o.room||'';$('height').value=o.height||'';$('width').value=o.width||'';layoutCols=o.layoutCols||1;layoutRows=o.layoutRows||1;panelConfigs=(o.panelConfigs||[]).map(x=>({...x}));const n=layoutCols*layoutRows;while(panelConfigs.length<n)panelConfigs.push({type:'',direction:''});hasTransom=!!o.hasTransom;transomPct=Number(o.transomPct||50);selectedPanel=0;show('builder');draw()}
function allowedTypes(){return typeFamilyMap[$('type').value]==='Door'?['Hinged Door','Sliding Door','Fixed']:TYPES}
function renderTypeButtons(){const box=$('typeButtons');box.innerHTML='';allowedTypes().forEach(t=>{const b=document.createElement('button');b.type='button';b.textContent=t==='Fixed'?'F — Fixed':t;b.className=panelConfigs[selectedPanel]?.type===t?'active':'';b.onclick=()=>selectPanelType(t);box.appendChild(b)})}
function selectPanelType(t){panelConfigs[selectedPanel]={type:t,direction:t==='Fixed'?'Fixed':''};renderTypeButtons();draw()}
function panelGeometry(i){const row=Math.floor(i/layoutCols),col=i%layoutCols;return {row,col}}
function mark(type){const stroke='stroke="currentColor" stroke-width="5" fill="none" stroke-linecap="round" stroke-linejoin="round"';if(!type)return '';if(type==='Fixed')return '<span class="mark f">F</span>';if(type==='Awning')return `<span class="mark"><svg viewBox="0 0 100 100"><path ${stroke} d="M5 5 L50 95 L95 5"/></svg></span>`;if(type==='Casement'||type==='Hinged Door')return `<span class="mark"><svg viewBox="0 0 100 100"><path ${stroke} d="M5 50 L95 5 M5 50 L95 95"/></svg></span>`;if(type==='Double Hung')return `<span class="mark"><svg viewBox="0 0 100 100"><line ${stroke} x1="5" y1="50" x2="95" y2="50"/><path ${stroke} d="M50 45 L50 10 M43 18 L50 10 L57 18 M50 55 L50 90 M43 82 L50 90 L57 82"/></svg></span>`;if(type==='Sliding Door')return `<span class="mark"><svg viewBox="0 0 100 100"><path ${stroke} d="M20 50 H80 M80 50 L67 38 M80 50 L67 62"/></svg></span>`;if(type==='Bifold')return `<span class="mark"><svg viewBox="0 0 100 100"><path ${stroke} d="M15 15 L50 50 L15 85 M85 15 L50 50 L85 85"/></svg></span>`;return ''}
function draw(){const d=$('drawing');d.className='drawing'+(layoutRows===2?' rows2':'');d.style.gridTemplateColumns=`repeat(${layoutCols},1fr)`;d.style.gridTemplateRows=`repeat(${layoutRows},1fr)`;d.innerHTML='';const n=layoutCols*layoutRows;for(let i=0;i<n;i++){const g=panelGeometry(i),c=panelConfigs[i]||{type:'',direction:''},cell=document.createElement('div');cell.className='cell'+(g.col===layoutCols-1?' lastcol':'')+(g.row===layoutRows-1?' bottom':'')+(i===selectedPanel?' selected':'');cell.innerHTML=mark(c.type);cell.onclick=()=>{selectedPanel=i;draw();renderTypeButtons();$('panelEditor').classList.remove('hidden');$('selectedPanelLabel').textContent=`Panel ${i+1}`};d.appendChild(cell)}if(hasTransom){const line=document.createElement('div');line.className='transomLine';line.style.top=transomPct+'%';d.appendChild(line);const drag=document.createElement('div');drag.className='transomDrag';drag.style.top=transomPct+'%';drag.innerHTML='<span class="transomHandle">Drag transom</span>';drag.onpointerdown=startTransomDrag;d.appendChild(drag)}$('transomControls').classList.toggle('hidden',!hasTransom);$('transomRange').value=transomPct;$('transomLabel').textContent=`Transom at ${Math.round(transomPct)}%`;renderTypeButtons();$('selectedPanelLabel').textContent=`Panel ${selectedPanel+1}`;$('panelEditor').classList.remove('hidden')}
function startTransomDrag(e){e.preventDefault();const d=$('drawing');const move=ev=>{const r=d.getBoundingClientRect();const pct=Math.max(20,Math.min(80,((ev.clientY-r.top)/r.height)*100));transomPct=pct;$('transomRange').value=pct;$('transomLabel').textContent=`Transom at ${Math.round(pct)}%`;d.querySelector('.transomLine').style.top=pct+'%';d.querySelector('.transomDrag').style.top=pct+'%'};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function addTransom(){hasTransom=true;layoutRows=2;layoutCols=Math.max(1,layoutCols);const n=layoutCols*2;while(panelConfigs.length<n)panelConfigs.push({type:'',direction:''});transomPct=50;draw()}
function saveOpening(){if(panelConfigs.some(p=>!p.type)){alert('Tap each panel and choose Opening type or Fixed before saving.');return}const room=$('room').value.trim(),height=$('height').value.trim(),width=$('width').value.trim();if(!room||!height||!width){alert('Enter room, height and width first.');return}const types=[...new Set(panelConfigs.map(p=>p.type))];const data={room,height,width,type:types.join(' + '),layoutCols,layoutRows,panels:panelConfigs.length,hasTransom,transomPct,panelConfigs:panelConfigs.map(p=>({...p}))};if(editingOpening>=0)current.openings[editingOpening]=data;else current.openings.push(data);persist();editingOpening=-1;$('room').value='';$('height').value='';$('width').value='';show('job')}
function makeSaved(o){const d=document.createElement('div');d.className='savedDrawing'+(o.layoutRows===2?' rows2':'');d.style.gridTemplateColumns=`repeat(${o.layoutCols||1},1fr)`;d.style.gridTemplateRows=`repeat(${o.layoutRows||1},1fr)`;const n=(o.layoutCols||1)*(o.layoutRows||1);for(let i=0;i<n;i++){const {row,col}=panelGeometryFor(o,i),cell=document.createElement('div');cell.className='cell'+(col===o.layoutCols-1?' lastcol':'')+(row===o.layoutRows-1?' bottom':'');cell.innerHTML=mark((o.panelConfigs||[])[i]?.type||'');d.appendChild(cell)}if(o.hasTransom){const line=document.createElement('div');line.className='transomLine';line.style.top=(o.transomPct||50)+'%';d.appendChild(line)}return d}
function panelGeometryFor(o,i){return {row:Math.floor(i/(o.layoutCols||1)),col:i%(o.layoutCols||1)}}
function renderOpenings(){const el=$('openings');el.innerHTML='';if(!current.openings?.length){el.innerHTML='<div class="muted">No openings saved yet.</div>';return}current.openings.forEach((o,i)=>{const card=document.createElement('div');card.className='openingCard';card.innerHTML=`<b>Opening ${i+1} — ${esc(o.room)}</b><div class="muted">${esc(o.height)} × ${esc(o.width)} mm · ${esc(o.type)}</div>`;card.appendChild(makeSaved(o));const b=document.createElement('button');b.className='secondary wide gap';b.textContent='Edit Opening / Transom';b.onclick=()=>editOpening(i);card.appendChild(b);el.appendChild(card)})}
function voiceField(id){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){alert('Voice recognition works best in Chrome on Android.');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='en-AU';r.interimResults=false;r.maxAlternatives=1;r.onresult=e=>{const t=e.results[0][0].transcript.trim();$(id).value=id==='room'?t:(parseNumber(t)||t)};r.start()}
function parseNumber(s){const m=s.match(/\d+(?:\.\d+)?/);if(m)return m[0];const nums={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};let total=0,cur=0;for(const w of s.toLowerCase().replace(/-/g,' ').split(/\s+/)){if(nums[w]!=null)cur+=nums[w];else if(w==='hundred')cur*=100;else if(w==='thousand'){total+=cur*1000;cur=0}}return total+cur||''}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('newJobBtn').onclick=newJob;$('startNewBtn').onclick=newJob;$('recentBtn').onclick=()=>show('jobs');$('backHomeBtn').onclick=()=>show('home');$('newBack').onclick=()=>show('home');$('createJobBtn').onclick=createJob;$('jobsBack').onclick=()=>show('jobs');$('homeBack').onclick=()=>show('home');$('builderBack').onclick=()=>show('job');$('buildBtn').onclick=setupOpening;$('saveOpeningBtn').onclick=saveOpening;$('addTransomBtn').onclick=addTransom;$('transomRange').oninput=e=>{transomPct=Number(e.target.value);draw()};$('search').oninput=renderJobs;document.querySelectorAll('[data-layout]').forEach(b=>b.onclick=()=>setLayout(b.dataset.layout));document.querySelectorAll('[data-voice]').forEach(b=>b.onclick=()=>voiceField(b.dataset.voice));show('home');
